name: sample
on:
  push:
    branches:
      - main
      - releases/*
      
permissions:
  id-token: write   
  contents: read       
jobs:
  my_job:
    name: deploy to staging
    runs-on: ubuntu-22.04
    steps: 
    - name: Checkout code
      uses: actions/checkout@v4   
    - name: Azure Login
      uses: Azure/login@v2.3.0
      with:
           
        client-id: e8b48fab-a267-4787-8581-a861d93d22d7
        tenant-id: bf1ea6d6-1a42-4fc7-b801-aaddf0e26bfe
        subscription-id: 50d7f43f-63cc-4cf6-8829-1542e9da33ea
        enable-AzPSSession: true
        environment: azurecloud
        
    - name: HashiCorp - Setup Terraform
      uses: hashicorp/setup-terraform@v2.0.3
      with:
        terraform_version: latest


                   
    
